core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .forms import LoginForm
from . import views
#recordar el nombre de esta app para poder agregarlo a urls del proyecto principal
app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contacto/', views.contacto, name='contacto'),
    path('registro/', views.registro, name='registro'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    
]

entregafinal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('mensajes/', include('mensajes.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views

#recordar el nombre de esta app para poder agregarlo a urls del proyecto principal
app_name = 'item'

urlpatterns = [
    #incluyendo int:pk, el path espera el id del item para desplegar el view de detalles
    path('', views.items, name='items'),
    path('nuevo/', views.new, name='new'),
    path('<int:pk>/', views.detalle, name='detalle'),
    path('<int:pk>/editar', views.edit, name='editar'),
    path('<int:pk>/borrar', views.delete, name='borrar'),
]

mensajes/urls.py
from django.urls import path
from . import views

app_name = 'mensajes'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detalle, name='detalle'),
    path('nuevo/<int:item_pk>/', views.nueva_conversacion, name='nuevo'),
]

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Ingresa tu nombre de usuario',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Ingresa tu contraseña',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class Registro(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Ingresa tu nombre de usuario',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Ingresa tu dirección de mail',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Ingresa tu contraseña',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repite tu contraseña',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect
from item.models import Categoria, Item
from .forms import Registro

def index(request):
    #traigo 6 items que estan disponibles "no vendidos" y las categorias disponibles
    items = Item.objects.filter(vendido=False)[0:6]
    categorias = Categoria.objects.all()
    #agregamos items y categorias al context para que pueda representarlos
    return render(request, 'core/index.html', {
        'categorias': categorias,
        'items':items,
    })

def contacto(request):
    return render(request, 'core/contacto.html')

def registro(request):
    if request.method == 'POST':
        formulario = Registro(request.POST)
        
        if formulario.is_valid():
            formulario.save()
            
            return redirect('/login/')
    else:
        formulario = Registro()
    
    return render(request, 'core/registro.html',{
        'formulario': formulario
    })

core/templates/core/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>
    
    <title>{% block titulo %}{%endblock %} | NahueApp</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">NahueApp</a>

        <div class="space-x-6">
            <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Buscar</a>
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">Nuevo item</a>
            
            {% if request.user.is_authenticated %}
            <a href="{% url 'mensajes:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Mensajes</a>
            <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>

            {% else %}
            <a href="{% url 'core:registro' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Registrarse</a>
            <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6">

        {% block contenido %}

        {% endblock %}

    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class=""w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">Acerca de</h3>

            <p class="text-lg text-gray-500">La app elegida para vender y permutar tus productos!
        </div>

        <div class=""w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class"space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Acerca de</a></li>
                    <li><a href="{% url 'core:contacto' %}" class="text-lg text-teal-500 hover:text-teal-700">Contacto</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

core/templates/core/contacto.html
{% extends 'core/base.html' %}

{% block titulo %}Contacto{% endblock %}

{% block contenido %}
    <h1>Pagina de contacto</h1>
{% endblock%}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block titulo %}Inicio{% endblock %}

{% block contenido %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Últimos agregados</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detalle' item.id %}">
                        <div>
                            <img src="{{ item.imagen.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.nombre }}</h2>
                            <p class="text-gray-500">Precio: {{ item.precio }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categorías</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for categoria in categorias %}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ categoria.nombre }}</h2>
                        <p class="text-gray-500">{{ categoria.items.count }} artículos</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock%}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block titulo %}Login{% endblock %}

{% block contenido %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Usuario</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Contraseña</label><br>
            {{ form.password }}
        </div>

        {% if formulario.errors or formulario.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in formulario %}
                    {{ field.errors }}
                {% endfor %}
                {{ formulario.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Enviar</button>
    </form>
</div>
{% endblock%}

core/templates/core/registro.html
{% extends 'core/base.html' %}

{% block titulo %}Registro usuario{% endblock %}

{% block contenido %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Registrarse</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Usuario</label><br>
            {{ formulario.username}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ formulario.email}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Contraseña</label><br>
            {{ formulario.password1}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repita contraseña</label><br>
            {{ formulario.password2}}
        </div>

        {% if formulario.errors or formulario.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in formulario %}
                    {{ field.errors }}
                {% endfor %}

                {{ formulario.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Enviar</button>
    </form>
</div>
{% endblock%}