core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .forms import LoginForm
from . import views
#recordar el nombre de esta app para poder agregarlo a urls del proyecto principal
app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contacto/', views.contacto, name='contacto'),
    path('registro/', views.registro, name='registro'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

entregafinal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('mensajes/', include('mensajes.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views

#recordar el nombre de esta app para poder agregarlo a urls del proyecto principal
app_name = 'item'

urlpatterns = [
    #incluyendo int:pk, el path espera el id del item para desplegar el view de detalles
    path('', views.items, name='items'),
    path('nuevo/', views.new, name='new'),
    path('<int:pk>/', views.detalle, name='detalle'),
    path('<int:pk>/editar', views.edit, name='editar'),
    path('<int:pk>/borrar', views.delete, name='borrar'),
]

mensajes/urls.py
from django.urls import path
from . import views

app_name = 'mensajes'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detalle, name='detalle'),
    path('nuevo/<int:item_pk>/', views.nueva_conversacion, name='nuevo'),
]

item/models.py
from django.db import models
from django.contrib.auth.models import User

class Categoria(models.Model):
    nombre = models.CharField(max_length=255)
    
    #Me permite agregar parametro de orden alfabetico
    class Meta:
        ordering = ('nombre',)
    
    #agregamos para poder ver nombres en la representacion de vista "admin"
    def __str__(self):
        return self.nombre
    
class Item(models.Model):
    #Puedo relacionar una categoria y agrupar los items, si se borra la categoria, se borran los items asociados
    categoria = models.ForeignKey(Categoria, related_name='items', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField(blank=True, null=True)
    precio = models.FloatField()
    imagen = models.ImageField(upload_to='item_imagen', blank=True, null=True)
    vendido = models.BooleanField(default=False)
    #Puedo relacionar usuario y agruparlos en varios items, si se borra el creador, se borra el item con el cascade
    creador = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    creado_fecha = models.DateField(auto_now_add=True)
    
    #Me permite agregar parametro de orden alfabetico
    class Meta:
        ordering = ('nombre',)
        
    #agregamos para poder ver nombres en la representacion de vista "admin"
    def __str__(self):
        return self.nombre

item/forms.py
from django import forms
from .models import Item

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('categoria', 'nombre', 'descripcion', 'precio', 'imagen')
        widgets = {
            'categoria': forms.Select(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'nombre': forms.TextInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'descripcion': forms.Textarea(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'precio': forms.TextInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'imagen': forms.FileInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            })
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('nombre', 'descripcion', 'precio', 'imagen', 'vendido')
        widgets = {
            'nombre': forms.TextInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'descripcion': forms.Textarea(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'precio': forms.TextInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'imagen': forms.FileInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            })
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Item, Categoria
from .forms import NewItemForm, EditItemForm
#importamos para poder realizar busquedas a fondo sobre la base de datos
from django.db.models import Q

def items(request):
    busqueda = request.GET.get('busqueda', '')
    categoria_id = request.GET.get('categoria', 0)
    categorias = Categoria.objects.all()
    items = Item.objects.filter(vendido=False)
    
    if categoria_id:
        items = items.filter(categoria_id=categoria_id)
    
    if busqueda:
        items = items.filter(Q(nombre__icontains=busqueda))
        
    return render(request, 'item/items.html',{
        'items': items,
        'busqueda': busqueda,
        'categorias': categorias,
        'categoria_id': int(categoria_id),
    })

def detalle(request, pk):
    #se pasa por parametro el id del item a buscar
    item = get_object_or_404(Item, pk=pk)
    #traemos 3 items relacionados de la misma categoria, filtrado por "no vendidos"
    items_relacionados = Item.objects.filter(categoria=item.categoria, vendido=False).exclude(pk=pk)[0:3]
    
    return render(request, 'item/detalle.html',{
        'item': item,
        'items_relacionados': items_relacionados
    })
    
@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        
        if form.is_valid():
            item = form.save(commit=False)
            item.creador = request.user
            item.save()
            
            return redirect('item:detalle', pk=item.id)
    else:
        form = NewItemForm()
        
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Nuevo item'
    })

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, creador=request.user)
    
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        
        if form.is_valid():
            form.save()
            
            return redirect('item:detalle', pk=item.id)
    else:
        form = EditItemForm(instance=item)
        
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Editar item'
    })

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, creador=request.user)
    item.delete()
    
    return redirect('dashboard:index')

item/templates/item/detalle.html
{% extends 'core/base.html' %}

{% block titulo %} {{ item.nombre }} {% endblock %}

{% block contenido %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.imagen.url}}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.nombre }}</h1>
        <p class="text-gray-500"><strong>Precio: </strong>{{ item.precio }}</p>
        <p class="text-gray-500"><strong>Vendedor: </strong>{{ item.creador }}</p>

        {% if item.descripcion %}
            <p class="text-gray-700">
            <strong class="text-gray-500">Descripción: </strong><br>
            {{ item.descripcion }}
            </p>
        {% endif %}

        {% if request.user == item.creador  %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>Este es tu artículo</p>

                <a href="{% url 'item:editar' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Editar</a>
                <a href="{% url 'item:borrar' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Borrar</a>
            </div>
        {% else %}
        <a href="{% url 'mensajes:nuevo' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contactar al vendedor</a>
        {% endif %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Misma categoría</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in items_relacionados %}
            <div>
                <a href="{% url 'item:detalle' item.id %}">
                    <div>
                        <img src="{{ item.imagen.url }}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.nombre }}</h2>
                        <p class="text-gray-500">Precio: {{ item.precio }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block titulo %} {{ title }}{% endblock %}

{% block contenido %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if formulario.errors or formulario.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ formulario.non_field_errors }}
            </div>
        {% endif %}

        <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Enviar</button>
</form>
{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block titulo %}Items{% endblock %}

{% block contenido %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <div class="col-span-1">
                <form method="get" action="{% url 'item:items' %}">
                    <input name="busqueda" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ busqueda }}" placeholder="Buscar productos">

                    <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Buscar</button>
                </form>

                <hr class="my-6">

                <p class="font-semibold">Categorías</p>

                <ul>
                    {% for categoria in categorias %}
                        <li class="py-2 px-2 rounded-xl{% if categoria.id == categoria_id %} bg-gray-200 {% endif %}">
                            <a href="{% url 'item:items' %}?busqueda={{ busqueda }}&categoria={{ categoria.id }}">{{ categoria.nombre }}</a>
                        </li>

                    {% endfor %}
                </ul>

                <hr class="my-6">

                <p class="font-semibold">Borrar filtros</p>

                <ul>
                    <li>
                        <a href="{% url 'item:items' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Limpiar</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                    <div>
                        <a href="{% url 'item:detalle' item.id %}">
                            <div>
                                <img src="{{ item.imagen.url }}" class="rounded-t-xl">
                            </div>
    
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ item.nombre }}</h2>
                                <p class="text-gray-500">Precio: {{ item.precio }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}